version: '3.3'

services:
  mongo:
    image: mongo:5.0.10
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=guest
      - MONGO_INITDB_ROOT_PASSWORD=guest
      - MONGO_INITDB_DATABASE=project
    ports:
      - '27018:27017'
    volumes:
      - ./docker/mongo-data:/data/db
      - ./docker/mongo-config:/data/configdb

  minio:
    container_name: Minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=supersecret
    image: quay.io/minio/minio:latest
    ports:
      - '9010:9000'
      - '9011:9001'
    volumes:
      - ./docker/minio:/data
    restart: unless-stopped

networks:
  dev:
